version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:11
jobs:
  install:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: ~/repo
        paths: .
  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: Run tests
        command: npm test
  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/repo
    - run: npm run build
    - persist_to_workspace:
        root: ~/repo
        paths: .
  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
    - run:
        name: Publish package
        command: npm publish
workflows:
  version: 2
  test-build-and-deploy:
    jobs:
    - install
    - test:
        requires:
        - install
    - build:
        requires:
        - install
    - deploy:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
