name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_versions
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - id: node-version
        run: echo "::set-output name=version=$(cat .node-version)"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - run: npm install
      - run: npm run build
