name: publish
on:
  release:
    types:
      - released
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_versions
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - id: node-version
        run: echo "::set-output name=version=$(cat .node-version)"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.output.version }}
      - run: npm install
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
